config/routes.rb
Birfday::Application.routes.draw do

  root :to => 'birthdays#index'

  resources :birthdays, only: [:index, :new, :create, :show]

end

app/models/birthday.rb
# == Schema Information
#
# Table name: birthdays
#
#  id          :integer          not null, primary key
#  url_hash    :string(255)
#  fb_url      :string(255)
#  twitter_url :string(255)
#  date_born   :datetime
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Birthday < ActiveRecord::Base
  extend FriendlyId
  friendly_id :url_hash

  attr_accessible :date_born, 
                  :name, 
                  :twitter_url, 
                  :url_hash

  acts_as_birthday :date_born

  validates_presence_of :date_born, :name, :url_hash
  validates_uniqueness_of :url_hash

  def set_twitter_handle
    twitter_account = self.twitter_url
    if twitter_account.include?('twitter.com')
      handle = twitter_account[/twitter\.com\/([a-zA-Z_]+)/,1]
    elsif twitter_account.include?('@')
      handle = twitter_account.sub('@', '')
    else
      handle = twitter_account
    end
    self.twitter_url = handle
  end

  def twitter_message
    if self.twitter_url.present?
      "IS IT @#{self.twitter_url} #BIRFDAY?"
    else
      "IS IT #{self.name.upcase}'s #BIRFDAY?"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/birthdays_controller.rb
class BirthdaysController < ApplicationController

  def index
    @lucky_one = Birthday.select { |x| x.date_born_today? }.sample
  end

  def new
    @birthday = Birthday.new
  end

  def create
    @birthday = Birthday.new(params[:birthday])
    @birthday.set_twitter_handle if params[:birthday][:twitter_url]
    @birthday.url_hash = SecureRandom.hex(3)
    if @birthday.save
      begin
        Twitter.update(@birthday.twitter_message + " #{birthday_url(@birthday)}")
      end
      redirect_to @birthday
    else
      render :new
    end
  end

  def show
    @birthday = Birthday.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s.upcase
  end

  def birthday_presenter
    @birthday.date_born.strftime('%m-%d')
  end

  def congratulate
    if @birthday.date_born == Date.today && @birthday.twitter_url.present?
      render partial: 'birthdays/tweet', locals: { handle: @birthday.twitter_url, url_site: birthday_url(@birthday) }
    end
  end

  def show_lucky_one
    if @lucky_one
      link_to "it's #{@lucky_one.name}'s birthday today", birthday_path(@lucky_one)
    else
      "seems like no one was born today"
    end
  end
end

app/views/birthdays/_tweet.html.erb
<%= link_to "Tweet to @#{handle}", "https://twitter.com/intent/tweet?screen_name=#{handle}", class: 'twitter-mention-button', data: { text: "IT'S YO BIRFDAY #{url_site}", lang: 'en', via: 'whosebirfday' } %>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/birthdays/index.html.erb
<% title "WHOSE BIRFDAY?" %>

<div class="sixteen columns first">
  <h1>let the world know it's someone's birthday</h1>
  <%= link_to 'Create A Birthday Page', new_birthday_path, class: 'button' %>
  <hr>
</div>

<div class="sixteen columns">
  <h2><%= show_lucky_one %></h2>
</div>

app/views/birthdays/new.html.erb
<% title "create a birthday page" %>

<div class="first sixteen columns clearfix">
  <h4 class="create-birthday">Create Someone's Birthday Page</h4>
  <%= simple_form_for @birthday do |f| %>
    <div class="six columns alpha">
      <%= f.input :date_born, label: 'birthday', required: false, discard_year: true, discard_hour: true, order: [:month, :day] %>
      <%= f.error :name, id: 'name-error' %>
      <%= f.input :name, label: "name of birthday person", required: false, error: false  %>
      <%= f.input :twitter_url, as: :string, label: 'twitter username of birthday person', placeholder: '@whosebirfday' %>
      <%= f.button :submit, class: 'create-birthday' %>  
    </div>
  <% end %>
</div>

app/views/birthdays/show.html.erb
<% content_for :page_specific_js do %>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.3.1/moment.min.js" type="text/javascript" ></script>
<% end %>


<% title "IS IT #{@birthday.name}'S BIRTHDAY?" %>

<div class="sixteen columns in-the-middle first">
  <h6 class="row-space"><%= "is it #{@birthday.name}'s birthday today?" %></h6>
  <br class='clear'>
  <h1 class="verdict" data-date="<%= birthday_presenter %>"></h1>
  <br class='clear'>
  <div class="tweet-button">
    <%= congratulate %>
  </div>
  <br class='clear'>
  <h6 class="row-space">share this birthday link: <%= link_to birthday_url(@birthday), @birthday_url %></h6>
  <%= link_to 'Make A New Birthday Page', new_birthday_path, class: 'button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= yield :page_specific_js %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="description" content="birfday.me lets the world know when it's someone's birthday. boom.">
  <meta name="author" content="adrian">
  <!-- Mobile Specific Metas
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <div class="container">
    <%= yield %>

    <footer class="sixteen columns in-the-middle">
      <h6>
        <%= link_to 'home', root_path %> | <%= link_to 'whose@birfday.me', 'mailto:whose@birfday.me' %> | hacked one night
      </h6>
    </footer>
  </div>
</body>
</html>